extends: airbnb-base
env:
  browser: true
  jest: true
rules:
  # These two rules interfere with Parcel absolute imports
  import/no-absolute-path: off
  import/no-unresolved: off
  no-console: off
  # We need this to make expando pattern work with type checking
  dot-notation: off
  semi:
    - error
    - never
