version: '3'
services:
    game:
        image: 'node:10.16'
        working_dir: /game
        command: ["sh", "./run-dev.sh"]
        volumes:
            - ./game:/game
            - ./common:/common
        environment:
            - CONTROLLER_HOST=${CONTROLLER_HOST}
            - ERROR_LOGGING=${ERROR_LOGGING}
            - HTTP_ADDRESS=${HTTP_ADDRESS}
            - VERSION=${VERSION}
            - WS_ADDRESS=${WS_ADDRESS}
        ports:
            - '8081:8081'
            - '8082:8082' # hot reload

    controller:
        image: 'node:10.16'
        working_dir: /controller
        command: ["sh", "./run-dev.sh"]
        volumes:
          - ./controller:/controller
          - ./common:/common
        environment:
            - REACT_APP_ERROR_LOGGING=${REACT_APP_ERROR_LOGGING}
            - REACT_APP_VERSION=${REACT_APP_VERSION}
            - REACT_APP_WS_ADDRESS=${REACT_APP_WS_ADDRESS}
        ports:
            - '4001:4001'
